### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [mariaozamiz/modulo-1-evaluacion-intermedia-mariaozamiz#1]
Muy buen trabajo @mariaozamiz!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 246 / 347
- [x] CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./styles/` o `./css/`.
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Necesitamos dos etiquetas `a` en el menu, dentro de los `li`.
- [x] HTML > MAIN: Necesitamos al menos una etiqueta `h1`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.header { align-items: center }`
- [x] CSS > COLOR: El color del h1 debe ser blanco
- [x] CSS > FONT-FAMILY: La fuente del h1 debe ser Rubik
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FLEX: El texto Creando diversidad digital debe estar centrado horizontal y verticalmente, lo mejor es hacerlo con flex.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by mariaozamiz** [comment]
Hola @migueldelmazo,

¡Muchas gracias!  Me he puesto con la corrección y ya pinta mejor. Solo tengo una duda: ¿a qué te refieres con "HTML>LINK debemos tener dos ficheros de estilos importados con un link"?

Gracias :)

**Comment by migueldelmazo** [comment]
Hola @mariaozamiz, en autocorrecto considera que tienes que tener dos y solo dos ficheros links styles. Tú tenías 3. Pero está bien porque tenías reset, styles y fuentes.

```
<link rel="stylesheet" href="./stylesheets/reset.css" />
<link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2 family=Rubik:wght@300;400;700;900&display=swap"
        />
<link rel="stylesheet" href="./stylesheets/main.css" />
```

Por ello no hagas caso a ese error.
